/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "劝君惜取少年时",
  "description": "Loading...",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "生命不止，奋斗不息",
        "tagline": "Miko Yan",
        "heroImage": "/walk.gif",
        "heroImageStyle": {
          "maxWidth": "150px",
          "width": "100%",
          "display": "block",
          "margin": "0 auto 2rem",
          "borderRadius": "1rem"
        },
        "bgImageStyle": {
          "height": "450px"
        },
        "isShowTitleInHome": false,
        "actionText": "Guide",
        "actionLink": "/views/other/guide",
        "features": [
          {
            "title": "Yesterday",
            "details": "昨天"
          },
          {
            "title": "Today",
            "details": "今天"
          },
          {
            "title": "Tomorrow",
            "details": "明天"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6efbadd8",
      "path": "/",
      "lastUpdated": "12/7/2021, 3:34:31 PM"
    },
    {
      "title": "async await关键字的使用",
      "frontmatter": {
        "title": "async await关键字的使用",
        "date": "2021-11-24T00:00:00.000Z",
        "categories": [
          "JS"
        ],
        "tags": [
          "JS"
        ]
      },
      "regularPath": "/blogs/categories/JS/JS_01.html",
      "relativePath": "blogs/categories/JS/JS_01.md",
      "key": "v-171fd64c",
      "path": "/blogs/categories/JS/JS_01.html",
      "headers": [
        {
          "level": 3,
          "title": "async await",
          "slug": "async-await"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "Mockjs 使用",
      "frontmatter": {
        "title": "Mockjs 使用",
        "date": "2021-12-06T00:00:00.000Z",
        "categories": [
          "JS"
        ],
        "tags": [
          "JS"
        ]
      },
      "regularPath": "/blogs/categories/JS/mockjs.html",
      "relativePath": "blogs/categories/JS/mockjs.md",
      "key": "v-0d20bf84",
      "path": "/blogs/categories/JS/mockjs.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "一、mockjs的数据类型 及 语法规范",
          "slug": "一、mockjs的数据类型-及-语法规范"
        },
        {
          "level": 3,
          "title": "1. 属性值是字符串 String",
          "slug": "_1-属性值是字符串-string"
        },
        {
          "level": 3,
          "title": "2. 属性值是数字 Number",
          "slug": "_2-属性值是数字-number"
        },
        {
          "level": 3,
          "title": "3. 属性值是布尔型 Boolean",
          "slug": "_3-属性值是布尔型-boolean"
        },
        {
          "level": 3,
          "title": "4. 属性值是对象 Object",
          "slug": "_4-属性值是对象-object"
        },
        {
          "level": 3,
          "title": "5. 属性值是数组 Array",
          "slug": "_5-属性值是数组-array"
        },
        {
          "level": 3,
          "title": "6. 属性值是函数 Function",
          "slug": "_6-属性值是函数-function"
        },
        {
          "level": 3,
          "title": "7. 属性值是正则表达式 RegExp",
          "slug": "_7-属性值是正则表达式-regexp"
        },
        {
          "level": 2,
          "title": "二、 Mock.setup()",
          "slug": "二、-mock-setup"
        },
        {
          "level": 2,
          "title": "三、Mock.Random 扩展方法",
          "slug": "三、mock-random-扩展方法"
        },
        {
          "level": 2,
          "title": "四、mockjs获取前端传递的数据",
          "slug": "四、mockjs获取前端传递的数据"
        },
        {
          "level": 2,
          "title": "五、Mock.Random 扩展方法",
          "slug": "五、mock-random-扩展方法"
        }
      ],
      "lastUpdated": "12/6/2021, 3:26:24 PM"
    },
    {
      "title": "Scss的使用",
      "frontmatter": {
        "title": "Scss的使用",
        "date": "2021-12-06T00:00:00.000Z",
        "categories": [
          "css"
        ],
        "tags": [
          "css"
        ]
      },
      "regularPath": "/blogs/categories/Scss/scss_01.html",
      "relativePath": "blogs/categories/Scss/scss_01.md",
      "key": "v-38e13e9a",
      "path": "/blogs/categories/Scss/scss_01.html",
      "headers": [
        {
          "level": 2,
          "title": "SCSS 的使用",
          "slug": "scss-的使用"
        },
        {
          "level": 3,
          "title": "1.@mixin 和@include 的使用 混入",
          "slug": "_1-mixin-和-include-的使用-混入"
        },
        {
          "level": 3,
          "title": "2.@extend 的使用 继承",
          "slug": "_2-extend-的使用-继承"
        }
      ],
      "lastUpdated": "12/7/2021, 10:05:28 AM"
    },
    {
      "title": "服务器部署",
      "frontmatter": {
        "title": "服务器部署",
        "date": "2021-11-24T00:00:00.000Z",
        "categories": [
          "server"
        ],
        "tags": [
          "server"
        ]
      },
      "regularPath": "/blogs/categories/Server/sever.html",
      "relativePath": "blogs/categories/Server/sever.md",
      "key": "v-131aee4c",
      "path": "/blogs/categories/Server/sever.html",
      "headers": [
        {
          "level": 2,
          "title": "进度",
          "slug": "进度"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "初识react",
      "frontmatter": {
        "title": "初识react",
        "date": "2021-11-23T00:00:00.000Z",
        "categories": [
          "React"
        ],
        "tags": [
          "React"
        ]
      },
      "regularPath": "/blogs/categories/React/react.html",
      "relativePath": "blogs/categories/React/react.md",
      "key": "v-7cd2b24c",
      "path": "/blogs/categories/React/react.html",
      "headers": [
        {
          "level": 2,
          "title": "DOM概念",
          "slug": "dom概念"
        },
        {
          "level": 2,
          "title": "React基本使用",
          "slug": "react基本使用"
        },
        {
          "level": 3,
          "title": "hello React",
          "slug": "hello-react"
        },
        {
          "level": 3,
          "title": "练习",
          "slug": "练习"
        },
        {
          "level": 2,
          "title": "函数式组件",
          "slug": "函数式组件"
        },
        {
          "level": 2,
          "title": "类组件",
          "slug": "类组件"
        },
        {
          "level": 2,
          "title": "组件实例的三大核心属性",
          "slug": "组件实例的三大核心属性"
        },
        {
          "level": 3,
          "title": "state",
          "slug": "state"
        },
        {
          "level": 3,
          "title": "props",
          "slug": "props"
        },
        {
          "level": 3,
          "title": "refs",
          "slug": "refs"
        }
      ],
      "lastUpdated": "12/9/2021, 5:26:32 PM"
    },
    {
      "title": "Vue国际化配置",
      "frontmatter": {
        "title": "Vue国际化配置",
        "date": "2021-11-24T00:00:00.000Z",
        "categories": [
          "Vue"
        ],
        "tags": [
          "Vue2.0"
        ]
      },
      "regularPath": "/blogs/categories/Vue/vue_01.html",
      "relativePath": "blogs/categories/Vue/vue_01.md",
      "key": "v-280155d4",
      "path": "/blogs/categories/Vue/vue_01.html",
      "headers": [
        {
          "level": 3,
          "title": "Vue-i18n",
          "slug": "vue-i18n"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "Vuex语法糖、插槽、父子传值",
      "frontmatter": {
        "title": "Vuex语法糖、插槽、父子传值",
        "date": "2021-11-24T00:00:00.000Z",
        "categories": [
          "Vue"
        ],
        "tags": [
          "Vue2.0"
        ]
      },
      "regularPath": "/blogs/categories/Vue/vue_02.html",
      "relativePath": "blogs/categories/Vue/vue_02.md",
      "key": "v-3d5e01f4",
      "path": "/blogs/categories/Vue/vue_02.html",
      "headers": [
        {
          "level": 2,
          "title": "具名插槽",
          "slug": "具名插槽"
        },
        {
          "level": 2,
          "title": "作用域插槽：",
          "slug": "作用域插槽"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "工作知识",
      "frontmatter": {
        "title": "工作知识",
        "date": "2021-11-24T00:00:00.000Z",
        "categories": [
          "工作杂记"
        ],
        "tags": [
          "work"
        ]
      },
      "regularPath": "/blogs/categories/Work/work.html",
      "relativePath": "blogs/categories/Work/work.md",
      "key": "v-5dce1052",
      "path": "/blogs/categories/Work/work.html",
      "headers": [
        {
          "level": 2,
          "title": "tips",
          "slug": "tips"
        },
        {
          "level": 3,
          "title": "1.设置字体渐变",
          "slug": "_1-设置字体渐变"
        },
        {
          "level": 3,
          "title": "2.拖拽排序",
          "slug": "_2-拖拽排序"
        },
        {
          "level": 3,
          "title": "3.浏览器去掉滚动条",
          "slug": "_3-浏览器去掉滚动条"
        },
        {
          "level": 3,
          "title": "4.背景虚化",
          "slug": "_4-背景虚化"
        },
        {
          "level": 3,
          "title": "5.文本超出...",
          "slug": "_5-文本超出"
        },
        {
          "level": 3,
          "title": "6.解析GET参数",
          "slug": "_6-解析get参数"
        },
        {
          "level": 3,
          "title": "7.移动端去除点击背景",
          "slug": "_7-移动端去除点击背景"
        },
        {
          "level": 3,
          "title": "8.对象属性访问的两种方式",
          "slug": "_8-对象属性访问的两种方式"
        },
        {
          "level": 3,
          "title": "9.vue异步传参",
          "slug": "_9-vue异步传参"
        }
      ],
      "lastUpdated": "12/9/2021, 5:26:32 PM"
    },
    {
      "title": "初识Vue3",
      "frontmatter": {
        "title": "初识Vue3",
        "date": "2021-11-23T00:00:00.000Z",
        "categories": [
          "Vue"
        ],
        "tags": [
          "Vue3.0"
        ]
      },
      "regularPath": "/blogs/categories/Vue/vue.html",
      "relativePath": "blogs/categories/Vue/vue.md",
      "key": "v-4ef83070",
      "path": "/blogs/categories/Vue/vue.html",
      "headers": [
        {
          "level": 2,
          "title": "1.Vue3简介",
          "slug": "_1-vue3简介"
        },
        {
          "level": 2,
          "title": "2.Vue3带来了什么",
          "slug": "_2-vue3带来了什么"
        },
        {
          "level": 3,
          "title": "1.性能的提升",
          "slug": "_1-性能的提升"
        },
        {
          "level": 3,
          "title": "2.源码的升级",
          "slug": "_2-源码的升级"
        },
        {
          "level": 3,
          "title": "3.拥抱TypeScript",
          "slug": "_3-拥抱typescript"
        },
        {
          "level": 3,
          "title": "4.新的特性",
          "slug": "_4-新的特性"
        },
        {
          "level": 2,
          "title": "1.使用 vue-cli 创建",
          "slug": "_1-使用-vue-cli-创建"
        },
        {
          "level": 2,
          "title": "2.使用 vite 创建",
          "slug": "_2-使用-vite-创建"
        },
        {
          "level": 2,
          "title": "1.拉开序幕的setup",
          "slug": "_1-拉开序幕的setup"
        },
        {
          "level": 2,
          "title": "2.ref函数",
          "slug": "_2-ref函数"
        },
        {
          "level": 2,
          "title": "3.reactive函数",
          "slug": "_3-reactive函数"
        },
        {
          "level": 2,
          "title": "4.Vue3.0中的响应式原理",
          "slug": "_4-vue3-0中的响应式原理"
        },
        {
          "level": 3,
          "title": "vue2.x的响应式",
          "slug": "vue2-x的响应式"
        },
        {
          "level": 3,
          "title": "Vue3.0的响应式",
          "slug": "vue3-0的响应式"
        },
        {
          "level": 2,
          "title": "5.reactive对比ref",
          "slug": "_5-reactive对比ref"
        },
        {
          "level": 2,
          "title": "6.setup的两个注意点",
          "slug": "_6-setup的两个注意点"
        },
        {
          "level": 2,
          "title": "7.计算属性与监视",
          "slug": "_7-计算属性与监视"
        },
        {
          "level": 3,
          "title": "1.computed函数",
          "slug": "_1-computed函数"
        },
        {
          "level": 3,
          "title": "2.watch函数",
          "slug": "_2-watch函数"
        },
        {
          "level": 3,
          "title": "3.watchEffect函数",
          "slug": "_3-watcheffect函数"
        },
        {
          "level": 2,
          "title": "8.生命周期",
          "slug": "_8-生命周期"
        },
        {
          "level": 2,
          "title": "9.自定义hook函数",
          "slug": "_9-自定义hook函数"
        },
        {
          "level": 2,
          "title": "10.toRef",
          "slug": "_10-toref"
        },
        {
          "level": 2,
          "title": "1.shallowReactive 与 shallowRef",
          "slug": "_1-shallowreactive-与-shallowref"
        },
        {
          "level": 2,
          "title": "2.readonly 与 shallowReadonly",
          "slug": "_2-readonly-与-shallowreadonly"
        },
        {
          "level": 2,
          "title": "3.toRaw 与 markRaw",
          "slug": "_3-toraw-与-markraw"
        },
        {
          "level": 2,
          "title": "4.customRef",
          "slug": "_4-customref"
        },
        {
          "level": 2,
          "title": "5.provide 与 inject",
          "slug": "_5-provide-与-inject"
        },
        {
          "level": 2,
          "title": "6.响应式数据的判断",
          "slug": "_6-响应式数据的判断"
        },
        {
          "level": 2,
          "title": "1.Options API 存在的问题",
          "slug": "_1-options-api-存在的问题"
        },
        {
          "level": 2,
          "title": "2.Composition API 的优势",
          "slug": "_2-composition-api-的优势"
        },
        {
          "level": 2,
          "title": "1.Fragment",
          "slug": "_1-fragment"
        },
        {
          "level": 2,
          "title": "2.Teleport",
          "slug": "_2-teleport"
        },
        {
          "level": 2,
          "title": "3.Suspense",
          "slug": "_3-suspense"
        },
        {
          "level": 2,
          "title": "1.全局API的转移",
          "slug": "_1-全局api的转移"
        },
        {
          "level": 2,
          "title": "2.其他改变",
          "slug": "_2-其他改变"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "博客指南",
      "frontmatter": {
        "title": "博客指南",
        "date": "2021-11-20T00:00:00.000Z"
      },
      "regularPath": "/blogs/other/guide.html",
      "relativePath": "blogs/other/guide.md",
      "key": "v-5cb75766",
      "path": "/blogs/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "参考指南",
          "slug": "参考指南"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "12/9/2021, 5:34:54 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/guide.html",
      "relativePath": "docs/guide.md",
      "key": "v-b1f33ee0",
      "path": "/docs/guide.html",
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "title": "webpack基础配置",
      "frontmatter": {
        "title": "webpack基础配置",
        "date": "2021-11-23T00:00:00.000Z",
        "categories": [
          "webpack"
        ],
        "tags": [
          "webpack"
        ]
      },
      "regularPath": "/blogs/categories/Webpack/webpack.html",
      "relativePath": "blogs/categories/Webpack/webpack.md",
      "key": "v-228172d4",
      "path": "/blogs/categories/Webpack/webpack.html",
      "headers": [
        {
          "level": 2,
          "title": "进度",
          "slug": "进度"
        }
      ],
      "lastUpdated": "11/24/2021, 1:10:23 PM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JS Tags"
      },
      "regularPath": "/tag/JS/",
      "key": "v-e8d965c8",
      "path": "/tag/JS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "css Tags"
      },
      "regularPath": "/tag/css/",
      "key": "v-323b9794",
      "path": "/tag/css/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "server Tags"
      },
      "regularPath": "/tag/server/",
      "key": "v-642d6b62",
      "path": "/tag/server/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "React Tags"
      },
      "regularPath": "/tag/React/",
      "key": "v-cd52144c",
      "path": "/tag/React/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue2.0 Tags"
      },
      "regularPath": "/tag/Vue2.0/",
      "key": "v-fee16492",
      "path": "/tag/Vue2.0/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "work Tags"
      },
      "regularPath": "/tag/work/",
      "key": "v-13074a58",
      "path": "/tag/work/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue3.0 Tags"
      },
      "regularPath": "/tag/Vue3.0/",
      "key": "v-fee07bd4",
      "path": "/tag/Vue3.0/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "webpack Tags"
      },
      "regularPath": "/tag/webpack/",
      "key": "v-b53ec9e8",
      "path": "/tag/webpack/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JS Categories"
      },
      "regularPath": "/categories/JS/",
      "key": "v-35a53628",
      "path": "/categories/JS/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "css Categories"
      },
      "regularPath": "/categories/css/",
      "key": "v-7f0d6caa",
      "path": "/categories/css/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "server Categories"
      },
      "regularPath": "/categories/server/",
      "key": "v-71cbee6e",
      "path": "/categories/server/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "React Categories"
      },
      "regularPath": "/categories/React/",
      "key": "v-58d43d64",
      "path": "/categories/React/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Categories"
      },
      "regularPath": "/categories/Vue/",
      "key": "v-7f0789a7",
      "path": "/categories/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "工作杂记 Categories"
      },
      "regularPath": "/categories/%E5%B7%A5%E4%BD%9C%E6%9D%82%E8%AE%B0/",
      "key": "v-76b278e8",
      "path": "/categories/工作杂记/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "webpack Categories"
      },
      "regularPath": "/categories/webpack/",
      "key": "v-4b927980",
      "path": "/categories/webpack/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "Guide",
            "link": "/docs/guide/"
          }
        ]
      },
      {
        "text": "联系作者",
        "icon": "reco-message",
        "items": [
          {
            "text": "Gitee",
            "link": "https://gitee.com/tonystark0",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {
      "/blogs/categories/Vue/": [
        "vue",
        "vue_01",
        "vue_02"
      ],
      "/blogs/categories/React/": [
        "react"
      ]
    },
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "Tag"
      }
    },
    "friendLink": [
      {
        "title": "Miko Yan",
        "desc": "Contact Author",
        "email": "1365813771@qq.com",
        "link": "tencent://message/?Site=baidu.com&uin=1365813771&Menu=yes"
      },
      {
        "title": "小猪校园跑腿",
        "desc": "一款集快递代拿、二手闲置、校园交友于一体的小程序",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "http://www.mikoyan.top"
      }
    ],
    "logo": "/book.png",
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "Last Updated",
    "author": "Miko Yan",
    "authorAvatar": "/avatar.png",
    "record": "渝ICP备2021013697号",
    "recordLink": "https://beian.miit.gov.cn/",
    "startYear": "2021",
    "valineConfig": {
      "appId": "qCotgRe6cJbrmI63r2fB0Ird-gzGzoHsz",
      "appKey": "8oNihGOQygEi3KNu8aL5daFB"
    }
  }
}