/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JS": {
      "key": "JS",
      "scope": "tags",
      "path": "/tag/JS/",
      "pageKeys": [
        "v-171fd64c",
        "v-0d20bf84"
      ]
    },
    "server": {
      "key": "server",
      "scope": "tags",
      "path": "/tag/server/",
      "pageKeys": [
        "v-131aee4c"
      ]
    },
    "css": {
      "key": "css",
      "scope": "tags",
      "path": "/tag/css/",
      "pageKeys": [
        "v-38e13e9a"
      ]
    },
    "React": {
      "key": "React",
      "scope": "tags",
      "path": "/tag/React/",
      "pageKeys": [
        "v-7cd2b24c"
      ]
    },
    "Vue2.0": {
      "key": "Vue2.0",
      "scope": "tags",
      "path": "/tag/Vue2.0/",
      "pageKeys": [
        "v-280155d4",
        "v-3d5e01f4"
      ]
    },
    "Vue3.0": {
      "key": "Vue3.0",
      "scope": "tags",
      "path": "/tag/Vue3.0/",
      "pageKeys": [
        "v-4ef83070"
      ]
    },
    "webpack": {
      "key": "webpack",
      "scope": "tags",
      "path": "/tag/webpack/",
      "pageKeys": [
        "v-228172d4"
      ]
    },
    "work": {
      "key": "work",
      "scope": "tags",
      "path": "/tag/work/",
      "pageKeys": [
        "v-5dce1052"
      ]
    }
  },
  "categories": {
    "JS": {
      "key": "JS",
      "scope": "categories",
      "path": "/categories/JS/",
      "pageKeys": [
        "v-171fd64c",
        "v-0d20bf84"
      ]
    },
    "server": {
      "key": "server",
      "scope": "categories",
      "path": "/categories/server/",
      "pageKeys": [
        "v-131aee4c"
      ]
    },
    "css": {
      "key": "css",
      "scope": "categories",
      "path": "/categories/css/",
      "pageKeys": [
        "v-38e13e9a"
      ]
    },
    "React": {
      "key": "React",
      "scope": "categories",
      "path": "/categories/React/",
      "pageKeys": [
        "v-7cd2b24c"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-280155d4",
        "v-4ef83070",
        "v-3d5e01f4"
      ]
    },
    "webpack": {
      "key": "webpack",
      "scope": "categories",
      "path": "/categories/webpack/",
      "pageKeys": [
        "v-228172d4"
      ]
    },
    "工作杂记": {
      "key": "工作杂记",
      "scope": "categories",
      "path": "/categories/工作杂记/",
      "pageKeys": [
        "v-5dce1052"
      ]
    }
  },
  "timeline": {}
}